version: "3.8"

services:
  nuxt:
    container_name: nuxt
    build:
      context: ${FRONTEND_CONTEXT}
      dockerfile: ../docker/frontend/Dockerfile
    ports:
      - ${APP_PORT:-3000}:3000
      - ${APP_PORT:-24678}:24678 # HMR用のポート
    tty: true
    stdin_open: true
    volumes:
      - ${FRONTEND_CONTEXT}:/workspace:cached
      - node_modules_volume:/workspace/node_modules
    environment:
      - HOST=0.0.0.0
      - CHOKIDAR_USEPOLLING=true

volumes:
  node_modules_volume:
