version: "3.8"

services:
  app:
    build:
      context: ${FRONTEND_CONTEXT}
      dockerfile: docker/Dockerfile
    ports:
      - ${APP_PORT:-3000}:3000
    tty: true
    stdin_open: true
    volumes:
      - ${FRONTEND_CONTEXT}:/app
      - node_modules_volume:/app/node_modules:delegated

volumes:
  node_modules_volume:
